[TAB-12547] Delayed messages
inPact/node-rabbitmq pull request #3
Opened 2021-07-21 14:23 UTC by nati-maskens

2021-07-25 16:02 UTC, joniba requested changes

2021-07-25 16:02 UTC, joniba commented on .travis.yml
> +  - DELAY_VERSION=3.8.0 DOCKER_COMPOSE_VERSION=1.29.2
line break?

2021-07-25 16:02 UTC, joniba commented on package.json
> +  "version": "3.0.1",
```suggestion
  "version": "3.1.0",
```

We mostly use patch versions to indicate hotfixes, or fixes in general.

2021-07-25 16:02 UTC, joniba commented on test/topology.spec.js
> +const { getFromApi } = common;
I try to discourage people from detaching methods from their containers, as it can lead to unexpected behavior and mainly to having to use `bind`. Seems like just an unnecessary confusion to add

2021-07-25 16:02 UTC, joniba commented on src/queues/distributed_queue.js
> +    async publishWithDelayTo(routingKey, message, options, delay) {
```suggestion
    async publishWithDelayTo(routingKey, message, delay, options) {
```

Since `delay` is not optional and `options` is optional, delay should come before, otherwise you force me to pass null arguments

2021-07-25 16:02 UTC, joniba commented on src/queues/distributed_queue.js
> +    async publishWithDelayTo(routingKey, message, options, delay) {
IMO, since the `publishTo` method already provides named options, adding a `publishWithDelayTo` is unnecessary. This really means that if in my development I decide to change from a regular channel to a delayed channel, that I need to refactor my publishers to use a different method. Why not just add the delayed option to the `publshTo`? Then you could (possibly later) add a `defaultDelay` configuration, so that in most cases I won't even need to worry about passing this parameter. Seems more flexible to me, and you could still provide descriptive error if you want.

2021-07-25 16:02 UTC, joniba commented on src/queues/distributed_queue.js
> +     * @param {number} delay Milliseconds to delay the message
```suggestion
     * @param {string} routingKey - the name of the queue or topic to publish to
     * @param {string} message - the message to publish
     * @param {*} [options] - the options to attach to the published message
     * @param {number} delay - Milliseconds to delay the message
```

2021-07-25 16:02 UTC, joniba commented on src/queues/distributed_queue.js
> +        if (!delay || !_.isNumber(delay)) throw new Error('cannot publish with delay without delay param (ms)');
I would like to see `ms` support here. It's much more user friendly.

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +    this.timeout(0);
?

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +const { getFromApi, cleanup, readDataFrom } = require('./common');
```suggestion
const common = require('./common');
```

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +                        name: 'topic.delay',
why type it out if you have a const for it?

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +        if (topicDelayExchange) await cleanup(broker, DELAY_TOPIC_NAME);
agh what are you saving the line breaks for? your grandkids?

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +        queueSection = broker.initQueue('testDelay');
it's not a queue section, but a queue wrapper. A section is a piece of a configuration, and doesn't have behavior, only data.

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +            // console.log('Arrived!', typeof message, routingKey, util.inspect(JSON.parse(message)), util.inspect(headers));
remove

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +            incomingMessages.push({ message, headers, routingKey });
I don't see a publisher in the test... why would a message arrive here?

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +        expect(topicDelayExchange).to.be.ok;
```suggestion
        expect(topicDelayExchange).to.exist;
```

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +        await queueSection.publishWithDelayTo('retry.86.order', 'Message 1', { headers: { 'x-foo': 'bar' } }, 12000);
this doesn't seem to be testing anything...?

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +        readDataFrom(incomingMessages, handleIncomingMessages, errors => {
I don't understand... why would this ever fail?

2021-07-25 16:02 UTC, joniba commented on test/delayed-messages.spec.js
> +            expect(handleIncomingMessages.callCount).to.equal(1);
I don't understand... where are the messages coming from? I don't see any publisher

2021-07-26 09:19 UTC, joniba reviewed
add release notes

2021-07-27 09:13 UTC, nati-maskens commented on src/queues/distributed_queue.js
> +     * @param {number} delay Milliseconds to delay the message
As we saw together, this is optional, and not even consistent across this repo. VSCode prefers without, so I keep.

2021-07-28 10:05 UTC, joniba commented on release_notes.md
> +## NEXT
If you have modified the version in the package.json, then you should have the same version in your release notes

2021-07-28 10:05 UTC, joniba commented on package.json
> +  "version": "3.1.0",
version numbers are usually only modified on master or via release branches

2021-07-28 12:48 UTC, closed without merging